import pygame as pg

pg.init()
ekraan = pg.display.set_mode((900,600))
ekraan.fill((200,150,150))

korgus = ekraan.get_height()
laius = ekraan.get_width()

tegelase_dimensioonid = (500,500)
lehtede_dimensioonid = (900,600)

menuu_algne = pg.image.load("pildid/menuu_algne copy.JPG")
menuu_algne = pg.transform.scale(menuu_algne,lehtede_dimensioonid)
menuu_alustame_mangu = pg.image.load("pildid/menuu_alustame_mangu copy.JPG")
menuu_alustame_mangu = pg.transform.scale(menuu_alustame_mangu,lehtede_dimensioonid)
menuu_kuidas_mang = pg.image.load("pildid/menuu_kuidas_mang copy.JPG")
menuu_kuidas_mang = pg.transform.scale(menuu_kuidas_mang,lehtede_dimensioonid)
menuu_aitab_kah = pg.image.load("pildid/menuu_aitab_kah copy.JPG")
menuu_aitab_kah = pg.transform.scale(menuu_aitab_kah,lehtede_dimensioonid)
menuu_kreditid = pg.image.load("pildid/menuu_kreditid copy.JPG")
menuu_kreditid = pg.transform.scale(menuu_kreditid,lehtede_dimensioonid)

kuidas_algne = pg.image.load("pildid/kuidas_algne copy.JPG")
kuidas_algne = pg.transform.scale(kuidas_algne,lehtede_dimensioonid)
kuidas_tagasi = pg.image.load("pildid/kuidas_tagasi copy.JPG")
kuidas_tagasi = pg.transform.scale(kuidas_tagasi,lehtede_dimensioonid)
alguses_kuidas = pg.image.load("pildid/alguses_kuidas copy.jpg")
alguses_kuidas = pg.transform.scale(alguses_kuidas,lehtede_dimensioonid)

layout = pg.image.load("pildid/layout_valitud copy.PNG")
layout = pg.transform.scale(layout,lehtede_dimensioonid)
layout_valitud = pg.image.load("pildid/layout copy.PNG")
layout_valitud = pg.transform.scale(layout_valitud,lehtede_dimensioonid)
paus_algus = pg.image.load("pildid/paus copy.JPG")
paus_algus = pg.transform.scale(paus_algus,lehtede_dimensioonid)
paus_tagasi = pg.image.load("pildid/paus_valitud copy.JPG")
paus_tagasi = pg.transform.scale(paus_tagasi,lehtede_dimensioonid)
paus_kuidas = pg.image.load("pildid/paus_kuidas copy.JPG")
paus_kuidas = pg.transform.scale(paus_kuidas,lehtede_dimensioonid)
paus_aitab = pg.image.load("pildid/paus_aitab copy.JPG")
paus_aitab = pg.transform.scale(paus_aitab,lehtede_dimensioonid)
paus_tanud = pg.image.load("pildid/paus_tanud copy.JPG")
paus_tanud = pg.transform.scale(paus_tanud,lehtede_dimensioonid)
mitmes_nadal = pg.image.load("pildid/nadal.JPG")
mitmes_nadal = pg.transform.scale(mitmes_nadal,lehtede_dimensioonid)

haircut_angry = pg.image.load("pildid/haircut_angry copy.png")
haircut_angry = pg.transform.scale(haircut_angry,tegelase_dimensioonid)
haircut_angry_home = pg.image.load("pildid/haircut_angry_home copy.png")
haircut_angry_home = pg.transform.scale(haircut_angry_home,tegelase_dimensioonid)
haircut_curious = pg.image.load("pildid/haircut_curious copy.png")
haircut_curious = pg.transform.scale(haircut_curious,tegelase_dimensioonid)
haircut_curious_home = pg.image.load("pildid/haircut_curious_home copy.png")
haircut_curious_home = pg.transform.scale(haircut_curious_home,tegelase_dimensioonid)
haircut_happy = pg.image.load("pildid/haircut_happy copy.png")
haircut_happy = pg.transform.scale(haircut_happy,tegelase_dimensioonid)
haircut_happy_home = pg.image.load("pildid/haircut_happy_home copy.png")
haircut_happy_home = pg.transform.scale(haircut_happy_home,tegelase_dimensioonid)
haircut_mus = pg.image.load("pildid/haircut_mus copy.png")
haircut_mus = pg.transform.scale(haircut_mus,tegelase_dimensioonid)
haircut_norm_home = pg.image.load("pildid/haircut_norm_home copy.png")
haircut_norm_home = pg.transform.scale(haircut_norm_home,tegelase_dimensioonid)
haircut_sad = pg.image.load("pildid/haircut_sad copy.png")
haircut_sad = pg.transform.scale(haircut_sad,tegelase_dimensioonid)
haircut_sad_home = pg.image.load("pildid/haircut_sad_home copy.png")
haircut_sad_home = pg.transform.scale(haircut_sad_home,tegelase_dimensioonid)
haircut_scared = pg.image.load("pildid/haircut_scared copy.png")
haircut_scared = pg.transform.scale(haircut_scared,tegelase_dimensioonid)
haircut_scared_home = pg.image.load("pildid/haircut_scared_home copy.png")
haircut_scared_home = pg.transform.scale(haircut_scared_home,tegelase_dimensioonid)
hoodie_angry = pg.image.load("pildid/hoodie_angry copy.png")
hoodie_angry = pg.transform.scale(hoodie_angry,tegelase_dimensioonid)
hoodie_curious = pg.image.load("pildid/hoodie_curious copy.png")
hoodie_curious = pg.transform.scale(hoodie_curious,tegelase_dimensioonid)
hoodie_happy = pg.image.load("pildid/hoodie_happy copy.png")
hoodie_happy = pg.transform.scale(hoodie_happy,tegelase_dimensioonid)
hoodie_mus = pg.image.load("pildid/hoodie_mus copy.png")
hoodie_mus = pg.transform.scale(hoodie_mus,tegelase_dimensioonid)
hoodie_norm = pg.image.load("pildid/hoodie_norm copy.png")
hoodie_norm = pg.transform.scale(hoodie_norm,tegelase_dimensioonid)
hoodie_sad = pg.image.load("pildid/hoodie_sad copy.png")
hoodie_sad = pg.transform.scale(hoodie_sad,tegelase_dimensioonid)
hoodie_scared = pg.image.load("pildid/hoodie_scared copy.png")
hoodie_scared = pg.transform.scale(hoodie_scared,tegelase_dimensioonid)
hoodie_work = pg.image.load("pildid/hoodie_work copy.png")
hoodie_work = pg.transform.scale(hoodie_work,tegelase_dimensioonid)
norm_angry = pg.image.load("pildid/norm_angry copy.png")
norm_angry = pg.transform.scale(norm_angry,tegelase_dimensioonid)
norm_curious = pg.image.load("pildid/norm_curious copy.png")
norm_curious = pg.transform.scale(norm_curious,tegelase_dimensioonid)
norm_happy = pg.image.load("pildid/norm_happy copy.png")
norm_happy = pg.transform.scale(norm_happy,tegelase_dimensioonid)
norm_mus = pg.image.load("pildid/norm_mus copy.png")
norm_mus = pg.transform.scale(norm_mus,tegelase_dimensioonid)
norm_norm = pg.image.load("pildid/norm_norm copy.png")
norm_norm = pg.transform.scale(norm_norm,tegelase_dimensioonid)
norm_sad = pg.image.load("pildid/norm_sad copy.png")
norm_sad = pg.transform.scale(norm_sad,tegelase_dimensioonid)
norm_scared = pg.image.load("pildid/norm_scared copy.png")
norm_scared = pg.transform.scale(norm_scared,tegelase_dimensioonid)
norm_work = pg.image.load("pildid/norm_work copy.png")
norm_work = pg.transform.scale(norm_work,tegelase_dimensioonid)
norm_write = pg.image.load("pildid/norm_write copy.png")
norm_write = pg.transform.scale(norm_write,tegelase_dimensioonid)

pop_curious = pg.image.load("pildid/pop_curious.png")
pop_curious = pg.transform.scale(pop_curious,tegelase_dimensioonid)
pop_happy = pg.image.load("pildid/pop_happy.png")
pop_happy = pg.transform.scale(pop_happy,tegelase_dimensioonid)
pop_norm = pg.image.load("pildid/pop_norm.png")
pop_norm = pg.transform.scale(pop_norm,tegelase_dimensioonid)
pop_sad = pg.image.load("pildid/pop_sad.png")
pop_sad = pg.transform.scale(pop_sad,tegelase_dimensioonid)